### PR TITLE
Updated to MC 1.15.2

### PR DESCRIPTION
**Pull request by Frettarix**
Changed the values so that they work in 1.15.2, blockId was changed to itemId.

### CODE REVIEW

**Comment by G07cha** [comment]
Thanks for PR. One thing that concerns me, those changes would break compatibility with older versions of Minecraft. To keep it with older versions and prevent from breaking in the future we can fetch correct ids from [minecraft-data](https://github.com/PrismarineJS/minecraft-data). I'll take a look at it later today to see if I can come up with anything sufficient.

**Comment by Frettarix** [comment]
Ah dang, forgot about that... perhaps you could specify this in the config object so you have a single point of configuration?

**Comment by G07cha** [comment]
Also an option indeed but since we should have all needed data we can use version detected by bot and as long as API stays the same and minecraft-data keeps being updated we should be good. Otherwise, it could be quite cumbersome for a consumer to lookup and specify correct ids

**Comment by rom1504** [comment]
Yes would definitely be better to get the right IDs from mcdata, that's
what we do in mineflayer

**Comment by G07cha** [comment]
As discussed, I've done a bit of refactoring and pushed version using mcdata in #5

**Pull request closed without merging**
